version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: taskdb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge
